services:
  database:
    image: mysql:latest
    container_name: database
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    # restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}

  nodejs:
    build: . # ระบุตำแหน่ง Dockerfile ในโฟลเดอร์ backend
    container_name: nodejs
    # restart: always
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app             # bind‑mount โค้ดทั้งหมดเข้ามา
      # - node_modules:/usr/src/app/node_modules  # กันไม่ให้ node_modules ฝั่ง host ทับ
    depends_on:
      - database
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
volumes:
  mysql_data:
  # node_modules:   # <<< เพิ่มบรรทัดนี้เพื่อแยก node_modules ออกมาเป็น volume