services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}

  nodejs:
    build: . # ระบุตำแหน่ง Dockerfile ในโฟลเดอร์ backend
    container_name: nodejs
    restart: always
    ports:
      - "${PORT}:3000"
    volumes:
      # - .:/usr/src/app # ระบุตำแหน่งโฟลเดอร์ที่เก็บโค้ด Node.js
      - .:/usr/src/app             # bind‑mount โค้ดทั้งหมดเข้ามา
      - /usr/src/app/node_modules  # กันไม่ให้ node_modules ฝั่ง host ทับ
    depends_on:
      - database
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    develop:
      watch:
        - action: sync # Sync ไฟล์ทุกครั้งที่มีการเปลี่ยนแปลงใน ./backend
          path: ./backend # โฟลเดอร์จากเครื่องเรา (host)
          target: /usr/src/app #  path ใน container ที่โค้ดไปอยู่ (WORKDIR ใน Dockerfile)
          ignore:
            - node_modules/
            - .git/
            - .env
            - logs/
            - coverage/
        # Rebuild on package.json changes
        - action: rebuild
          path: ./backend/package.json

volumes:
  mysql_data: